; Script generated by AutoBuilder 0.9f Prototype

#region ---Head--
#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>

#include <EditConstants.au3>
#include <ButtonConstants.au3>
#include <StaticConstants.au3>

Global $hGUI,$ime_input,$id_input,$Continue,$Clear,$Search,$vnesi_ime_label,$id_input_label,$ico
create_form()
#endregion ---Head---

#region --- Form ---

func create_form()
$hGUI=GuiCreate("MyGUI", 500, 400, -1, -1, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)

$ime_input = GuiCtrlCreateInput("", 10, 20, 270, 40,-1)
$id_input = GuiCtrlCreateInput("", 10, 100, 270, 40,-1)
$Continue = GuiCtrlCreateButton("Continue", 410, 160, 70, 30,-1)
$Clear = GuiCtrlCreateButton("Clear", 80, 160, 70, 30,-1)
$Search = GuiCtrlCreateButton("Search", 10, 160, 70, 30,-1)
$vnesi_ime_label = GuiCtrlCreateLabel("Vnesi ime na firma", 310, 30, 170, 30,-1)
$id_input_label = GuiCtrlCreateLabel("Vnesi ID na firma", 310, 110, 170, 30,-1)
$ico = GuiCtrlCreatePic("C:\CDEPS\KASPER.ico", 20, 70, 20, 20,-1)

GuiSetState()
endfunc
#EndRegion --- Form ---

#region --- Loop ---
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	EndSelect
WEnd
#Endregion --- Loop ---

#Region --- Additional Functions ---
#Endregion --- Additional Functions ---

Exit

