; Script generated by AutoBuilder 0.9f Prototype

#region ---Head--
#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>

#include <StaticConstants.au3>

Global $hGUI,$Label_4,$Label_8,$Label_9,$Label_10,$Label_11,$Label_12
create_form()
#endregion ---Head---

#region --- Form ---

func create_form()
$hGUI=GuiCreate("MyGUI", 600, 400, -1, -1, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)

$Label_4 = GuiCtrlCreateLabel("Label_4", 20, 330, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)
$Label_8 = GuiCtrlCreateLabel("Label_8", 170, 330, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)
$Label_9 = GuiCtrlCreateLabel("Label_9", 320, 330, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)
$Label_10 = GuiCtrlCreateLabel("Label_10", 470, 330, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)
$Label_11 = GuiCtrlCreateLabel("Label_11", 160, 380, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)
$Label_12 = GuiCtrlCreateLabel("Label_12", 320, 380, 140, 20,-1)
GUICtrlSetBkColor(-1,8421504)

GuiSetState()
endfunc
#EndRegion --- Form ---

#region --- Loop ---
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	EndSelect
WEnd
#Endregion --- Loop ---

#Region --- Additional Functions ---
#Endregion --- Additional Functions ---

Exit

